<div class="content-wrapper">
    <section class="content">
        <div class="row">

            <div class="box">
                    <div class="box-header">
                        <div class="col-xs-8">
                            <h3 class="box-title">Add New User Form</h3>
                        </div>
                    </div>
                
                <div class="box-body">
                        <?php
                        $form = $this->form;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        foreach ($form as $element) :
                        ?>
                        <div class="form-group">
                            <label><?php echo $element-> getLabel();?></label>
                            <?php echo $this->formElement($element);?>
                        </div>
                        <?php
                        endforeach;
                        echo $this->form()->closeTag();
                        ?>
                </div>
            </div>

        </div>
    </section>
</div>


<script type="text/javascript">
$(document).ready(function () {           
});
</script>


