<div class="content-wrapper">
    <section class="content">
        <div class="row">

            <div class="col-sm-8">

                    <div class="box box-primary">
                        <div class="box-header">
                            <h3 class="box-title">Add New User Form</h3>
                        </div> 

                        <?php
                        $form = $this->form;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        foreach ($form as $element) :
                        ?>
                        <div class="form-group">
                            <label class="control-label col-sm-4"><?php echo $element-> getLabel();?></label>
                            <div class="col-sm-8"><?php echo $this->formElement($element);?></div>
                        </div>
                        <?php
                        endforeach;
                        echo $this->form()->closeTag();
                        ?>
                        
<!--                        <form class="form-horizontal" role="form">
                            <div class="form-group">
                                <label class="control-label col-sm-4">Email:</label>
                                <div class="col-sm-8">
                                    <input type="email" class="form-control" placeholder="Enter email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-4">Password:</label>
                                <div class="col-sm-8"> 
                                    <input type="password" class="form-control" placeholder="Enter password">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-4"></div>
                                <div class="col-sm-8">
                                    <button type="submit" class="btn btn-default">Submit</button>
                                </div>
                            </div>
                        </form>  -->

                    </div>

            </div>

        </div>
    </section>
</div>


<script type="text/javascript">
$(document).ready(function () {           
});
</script>


