<link href="<?php echo $this->basePath();?>/admin/bootstrap/css/custom.css" rel="stylesheet" type="text/css" />    

<div class="content-wrapper">
    <section class="content">
        <div class="row">

            <div class="col-sm-6 col-md-offset-3">

                    <div class="box box-primary clearfix">
                        <div class="box-header col-md-offset-1">
                            <h3 class="box-title">Add New User Form</h3>
                        </div> 

                        <?php
                        $form = $this->form;
                        $form->prepare();
                        echo $this->form()->openTag($form);
                        
                        foreach ($form as $element) :
                        ?>
                        <div class="form-group clearfix">
                            <label class="control-label col-sm-3 text-right <?php echo $element->getLabelAttributes()["class"];?> "><?php echo $element-> getLabel();?></label>
                            <div class="col-sm-8"><?php echo $this->formElement($element);?><?php echo  $this->formElementErrors($element)?></div>
                        </div>
                        <?php
                        endforeach;
                        echo $this->form()->closeTag();
                        ?>
                    </div>

            </div>
            

        </div>
    </section>
</div>


<script type="text/javascript">       
$(function () {
    $('#dob').datetimepicker();
});
$(document).ready(function () {           
});
</script>


