<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Forgot Password</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="<?php echo $this->basePath();?>/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />    
    <link href="<?php echo $this->basePath();?>/admin/dist/css/admin.min.css" rel="stylesheet" type="text/css" />   
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Forgot Password</b></a>
      </div>
      <div class="login-box-body">
        <p class="login-box-msg">We'll email you instructions on how to reset your password.</p>
        <form id="loginForm" action="<?php echo $this->basePath();?>/users/index/process-forgot-password" method="post">
          <div class="form-group has-feedback">
              <input id="userEmail" name="userEmail" type="email" class="form-control email" placeholder="Email" value="<?php if( isset($userEmail)){ echo $userEmail; }?>"  autocomplete="off"/>
            <span id="password" class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="row">            
            <div class="col-xs-6 col-xs-offset-3">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Forget Password</button>
            </div>
          </div>
        </form>
      </div>
    </div>
      
    <script src="<?php echo $this->basePath();?>/admin/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <script src="<?php echo $this->basePath();?>/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>    
  </body>
</html>