<link href="<?php echo $this->basePath();?>/admin/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />

<div class="content-wrapper">
    <section class="content">
        <div class="row">

            <div class="box">
                    <div class="box-header">
                        <div class="col-md-10">
                            <h3 class="box-title">Manage Users</h3>
                        </div>
                        <div class="col-md-2 col-xs-6">
                            <a class="btn btn-block btn-primary pull-left" href="<?php echo $this->basePath();?>/users/index/add-new-user"><i class="fa fa-plus-square-o"></i> Add New</a>
                        </div>                        
                    </div>
                
                <div class="box-body table-responsive">

                    <table id="usersTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>NAME</th>
                                <th>EMAIL</th>
                                <th>DOB</th>
                                <th>MOBILE</th>
                                <th>GENDER</th>
                                <th>STATUS</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach($this->userDetails as $userDetails)
                            {
                            ?>
                            <tr>
                                <td><?php echo $userDetails->userName; ?></td>
                                <td><?php echo $userDetails->userEmail; ?></td>
                                <td><?php echo $this->dateFormatIndia( $userDetails->userDob );?></td>
                                <td><?php echo $userDetails->userMobile; ?></td>
                                <td><?php echo $userDetails->userGender; ?></td>
                                <td><?php echo ($userDetails->userStatus == 1) ? 'Active' : 'Inactive';?></td>
                                <td>
                                    <form class="frm" method="post" action="#">
                                        <a class="btn edit"><i class="fa fa-edit"></i> Edit</a>
                                        <a class="btn delete"><i class="fa fa-times"></i> Delete</a>                                    
                                        <input type="hidden" name="userEmail" value="<?php echo $userDetails->userEmail; ?>">
                                    </form>
                                </td>
                            </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </section>
</div>

<form method="post" id="frm" action="">
    <input type="hidden" name="email" value="<?php echo $userDetails->email; ?>">
</form>


<script src="<?php echo $this->basePath();?>/admin/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath();?>/admin/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
    $('#usersTable').dataTable();    
});

$(document).ready(function () {    
    $(document).on('click','.edit',function(){
        var elem = $(this);
        var frm = elem.closest('tr').find('.frm');
        frm.attr('action','<?php echo $this->basePath();?>/users/index/update-user-profile');
        frm.submit();
    });
    $(document).on('click','.delete',function(){
        var elem = $(this);
        var frm = elem.closest('tr').find('.frm');
        frm.attr('action','<?php echo $this->basePath();?>/users/index/delete-user-profile');
        frm.submit();
    });
});
</script>


