<link href="<?php echo $this->basePath();?>/admin/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />

<div class="content-wrapper">
    <section class="content">
        <div class="row">

            <div class="box">
                    <div class="box-header">
                        <div class="col-xs-8">
                            <h3 class="box-title">Manage Users</h3>
                        </div>
                        <div class="col-xs-2">
                            <a class="btn btn-block btn-primary pull-left"><i class="fa fa-plus-square-o"></i> Add New</a>
                        </div>
                        <div class="col-xs-2">                            
                            <a class="btn btn-block btn-primary pull-left export"><i class="fa fa-download"></i> Download</a>
                        </div>
                    </div>
                
                <div class="box-body">

                    <table id="usersTable" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>NAME</th>
                                <th>EMAIL</th>
                                <th>DOB</th>
                                <th>MOBILE</th>
                                <th>GENDER</th>
                                <th>STATUS</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach($this->userDetails as $userDetails)
                            {
                            ?>
                            <tr>
                                <td><?php echo $userDetails->name; ?></td>
                                <td><?php echo $userDetails->email; ?></td>
                                <td><?php echo $this->dateFormatIndia( $userDetails->dob );?></td>
                                <td><?php echo $userDetails->mobile; ?></td>
                                <td><?php echo $userDetails->gender; ?></td>
                                <td><?php echo ($userDetails->status == 1) ? 'Active' : 'Inactive';?></td>
                                <td>
                                    <a class="btn"><i class="fa fa-edit"></i> Edit</a>
                                    <a class="btn"><i class="fa fa-times"></i> Delete</a>
                                </td>
                            </tr>
                            <?php
                            }
                            ?>
                        </tbody>
                    </table>

                </div>
            </div>

        </div>
    </section>
</div>

<input type="hidden" name="hiddenCsv" id="hiddenCsv" value="" />

<script src="<?php echo $this->basePath();?>/admin/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath();?>/admin/plugins/datatables/dataTables.bootstrap.js" type="text/javascript"></script>
<script src="<?php echo $this->basePath();?>/admin/dist/js/demo.js" type="text/javascript"></script>

<script type="text/javascript">
$(function () {
    $('#usersTable').dataTable();    
});

$(document).ready(function () {    
    $(".export").on('click', function (event) {        
        exportTableToCSV.apply(this, [$('#usersTable'), 'export.csv']);
    });    
});
</script>


