<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Admin | Log in</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="<?php echo $this->basePath();?>/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />    
    <link href="<?php echo $this->basePath();?>/admin/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath();?>/admin/plugins/iCheck/square/blue.css" rel="stylesheet" type="text/css" />
    <style>
        .error {
            color:red;
        }
        .valid {
            color:green;
        }
    </style>
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="../../index2.html"><b>Admin</b></a>
      </div>
      <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>
        <form id="loginForm" action="<?php echo $this->basePath();?>/users/index/process-login" method="post">
          <div class="form-group has-feedback">
              <input id="email" name="email" type="text" class="form-control email" placeholder="Email" value="<?php if( $this->email != null){ echo $this->email; }?>"/>
            <span id="password" class="glyphicon glyphicon-envelope form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            <input id="password" name="password" type="password" class="form-control password" placeholder="Password"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8">    
              <div class="checkbox icheck">
                <label>
                    <input id="rememberMe" name="rememberMe" type="checkbox" value="Yes"> Remember Me
                </label>
              </div>                        
            </div>
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
            </div>
          </div>
        </form>

        <div class="social-auth-links text-center">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using Facebook</a>
          <a href="#" class="btn btn-block btn-social btn-google-plus btn-flat"><i class="fa fa-google-plus"></i> Sign in using Google+</a>
        </div>

        <a href="<?php echo $this->basePath();?>/users/index/forgot-password">I forgot my password</a><br>
        <a href="<?php echo $this->basePath();?>/users/index/register" class="text-center">Register a new membership</a>

      </div>
    </div>
      
    <script src="<?php echo $this->basePath();?>/admin/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <script src="<?php echo $this->basePath();?>/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="<?php echo $this->basePath();?>/admin/plugins/iCheck/icheck.min.js" type="text/javascript"></script>   
  </body>
</html>