<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Reset Password</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="shortcut icon" href="<?php echo $this->basePath();?>/images/favicon.ico" type="text/css">
    <link href="<?php echo $this->basePath();?>/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />    
    <link href="<?php echo $this->basePath();?>/admin/dist/css/admin.min.css" rel="stylesheet" type="text/css" />    
  </head>
  <body class="login-page">
    <div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Reset Password</b></a>
      </div>
    
            
      <div class="login-box-body">
        <?php
        if($message == '')
        {
        ?>
          <p>Dear <?php echo $userName; ?>,</p>
          <p>You can reset your password using this form.</p>
        
        <form id="resetPasswordForm" name="resetPasswordForm" action="<?php echo $this->basePath();?>/users/index/process-reset-password" method="post">
          <div class="form-group has-feedback">
              <input id="password" name="password" type="password" class="form-control password" placeholder="Password" autocomplete="off"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
            <div class="form-group has-feedback">
              <input id="cnfPassword" name="cnfPassword" type="password" class="form-control password" placeholder="Confirm Password" autocomplete="off"/>
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-6 col-xs-offset-3">
                <input type="hidden" id="resetKey" name="resetKey" value="<?php echo $resetKey; ?>">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Reset Password</button>
            </div>
          </div>
        </form>
        <?php
        }
        else
        {
        ?>
          <p class="box-body">Key is not authentic.</p>    
        <?php
        }
        ?>
      </div>        
    </div>
      
    <script src="<?php echo $this->basePath();?>/admin/plugins/jQuery/jQuery-2.1.3.min.js"></script>
    <script src="<?php echo $this->basePath();?>/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>    
  </body>
</html>