<aside class="main-sidebar">
    <section class="sidebar">
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li><a href="<?php echo $this->basePath();?>/users/index/dashboard-super-admin"><i class="fa fa-circle-o text-info"></i> Dashboard</a></li>
            <li><a href="<?php echo $this->basePath();?>/authorization/serviceGoups/list-service-groups"><i class="fa fa-circle-o text-info"></i> Service Groups</a></li>
            <li><a href="<?php echo $this->basePath();?>/authorization/services/list-services"><i class="fa fa-circle-o text-info"></i> Services</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-info"></i> Authorization</a></li>
            <li><a href="<?php echo $this->basePath();?>/users/index/list-users"><i class="fa fa-circle-o text-info"></i> Users</a></li>
        </ul>
    </section>
</aside>