<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?php echo $this->userImagePath. $this->userDetails->image;?>" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p><?php echo $this->userDetails->name;?></p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
                <span class="input-group-btn">
                    <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </form>
        <ul class="sidebar-menu">
            <li><a href="#"><i class="fa fa-circle-o text-danger"></i> Service Groups</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Services</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-warning"></i> Authorization</a></li>
            <li><a href="#"><i class="fa fa-circle-o text-info"></i> Users</a></li>
        </ul>
    </section>
</aside>