<header class="main-header">
    <a href="index2.html" class="logo"><b><?php echo $this->getValue('user_types', 'userType', 'id', $this->userDetails->userTypeId ); ?></b></a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">      
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?php echo $this->layout()->getVariable('userImagePath'). $this->userDetails->userImage;?>" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?php echo $this->userDetails->userName;?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="<?php echo $this->layout()->getVariable('userImagePath'). $this->userDetails->userImage;?>" class="img-circle" alt="User Image" />
                            <p>
                            <?php echo $this->userDetails->userName;?>
                            <small>Member since <?php echo $this->dateFormatIndia( $this->userDetails->createdDateTime );?></small>
                            </p>
                        </li>            
                        <li class="user-footer">
                            <div class="pull-left">
                                <form class="frm" method="post" action="#">
                                    <a href="#" class="btn btn-default btn-flat profileLink">Profile</a>
                                    <input type="hidden" name="userEmail" value="<?php echo $this->userDetails->userEmail;?>">
                                </form>
                            </div>
                            <div class="pull-right">
                                <a href="<?php echo $this->basePath();?>/users/index/log-out" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

<script>
$(document).ready(function () {    
    $(document).on('click','.profileLink',function(){
        var elem = $(this);
        var frm = elem.closest('div').find('.frm');
        frm.attr('action','<?php echo $this->basePath();?>/users/index/update-user-profile');
        frm.submit();
    });    
});
</script>