<?php echo $this->doctype(); ?>

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="RAJESH PANERU">
        <meta name="author" content="RAJESH PANERU">        
                
        <link href="<?php echo $this->basePath();?>/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />    
        <link href="<?php echo $this->basePath();?>/admin/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/plugins/iCheck/flat/blue.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/plugins/morris/morris.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/plugins/datepicker/datepicker3.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/plugins/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />    
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />    
        

        <script src="<?php echo $this->basePath();?>/admin/plugins/jQuery/jQuery-2.1.3.min.js"></script>
<!--        <script>
          $.widget.bridge('uibutton', $.ui.button);
        </script>-->
        <script src="<?php echo $this->basePath();?>/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>            
        <script src="<?php echo $this->basePath();?>/admin/plugins/morris/morris.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/knob/jquery.knob.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/plugins/slimScroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src='<?php echo $this->basePath();?>/admin/plugins/fastclick/fastclick.min.js'></script>
        <script src="<?php echo $this->basePath();?>/admin/dist/js/app.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/js/exportTableToCSV.js" type="text/javascript"></script>        
        
<!--        <script src="<?php echo $this->basePath();?>/admin/dist/js/pages/dashboard.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/admin/dist/js/demo.js" type="text/javascript"></script> 
        <script src="<?php echo $this->basePath();?>/js/jquery.validate.min.js"></script>        --> 
    </head>

    <body class="skin-blue">
                
        <div class="wrapper">    
            
            <?php echo $this->render('partial/topMenu', array('userDetails'=>$userDetails) ); ?>
    
            <?php echo $this->render('partial/leftMenu', array('userDetails'=>$userDetails) ); ?>
      
            <?php echo $this->content; ?>     
      
            <?php echo $this-> partial('partial/footer');?>

        </div>
                
        
    </body>

</html>