<?php echo $this->doctype(); ?>

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="RAJESH PANERU">
        <meta name="author" content="RAJESH PANERU">        
                
        <link href="<?php echo $this->basePath();?>/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />    
        <link href="<?php echo $this->basePath();?>/admin/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath();?>/admin/dist/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />    
        
        <script src="<?php echo $this->basePath();?>/admin/plugins/jQuery/jQuery-2.1.3.min.js"></script>
        <script src="<?php echo $this->basePath();?>/admin/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>            
        <script src="<?php echo $this->basePath();?>/admin/dist/js/app.min.js" type="text/javascript"></script>
        <script src="<?php echo $this->basePath();?>/js/exportTableToCSV.js" type="text/javascript"></script>                 
    </head>

    <body class="skin-blue">
                
        <div class="wrapper">    
            
            <?php echo $this->render('partial/topMenu', array('userDetails'=>$userDetails) ); ?>
    
            <?php echo $this->render('partial/leftMenu', array('userDetails'=>$userDetails) ); ?>
      
            <?php echo $this->content; ?>     
      
            <?php echo $this-> partial('partial/footer');?>

        </div>
                
        
    </body>

</html>