<?php echo $this->doctype(); ?>

<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="RAJESH PANERU">
        <meta name="author" content="RAJESH PANERU">
        
        <title>RAJESH PANERU</title>
        <link href="<?php echo $this->basePath();?>/landing/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basePath();?>/landing/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href="<?php echo $this->basePath();?>/landing/css/animate.css" rel="stylesheet" />
        <link href="<?php echo $this->basePath();?>/landing/css/style.css" rel="stylesheet">
        <link href="<?php echo $this->basePath();?>/landing/color/default.css" rel="stylesheet">
        
        
        <script src="<?php echo $this->basePath();?>/js/jquery.min.js"></script>
        <script src="<?php echo $this->basePath();?>/landing/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->basePath();?>/landing/js/jquery.easing.min.js"></script>	
        <script src="<?php echo $this->basePath();?>/landing/js/jquery.scrollTo.js"></script>
        <script src="<?php echo $this->basePath();?>/landing/js/wow.min.js"></script>
        <script src="<?php echo $this->basePath();?>/landing/js/custom.js"></script>
        <script src="<?php echo $this->basePath();?>/js/jquery.validate.min.js"></script>
        
        <style>
        .error {
            color:red;
        }
        .valid {
            color:green;
        }
        </style>

    </head>

    <body id="page-top" data-spy="scroll" data-target=".navbar-custom">
        
        <div id="preloader">
            <div id="load"></div>
        </div>

        <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse"><i class="fa fa-bars"></i></button>
                    <a class="navbar-brand" href="<?php echo $this->basePath();?>"><h1>RAJESH PANERU</h1></a>
                </div>

                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#intro">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#service">Service</a></li>
                        <li><a href="#contact">Contact</a></li>
                        <li><a href="<?php echo $this->basePath();?>/users/index/login">Login</a></li>
                        <li><a href="<?php echo $this->basePath();?>/users/index/register">Register</a></li>
    <!--                    <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Example menu</a></li>
                                <li><a href="#">Example menu</a></li>
                                <li><a href="#">Example menu</a></li>
                            </ul>
                        </li>-->
                    </ul>
                </div>
            </div>
        </nav>
        
        <?php echo $this->content; ?>  


        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-lg-12">
                        <div class="wow shake" data-wow-delay="0.4s">
                            <div class="page-scroll marginbot-30">
                                <a href="#intro" id="totop" class="btn btn-circle"><i class="fa fa-angle-double-up animated"></i></a>
                            </div>
                        </div>
                        <p>&copy;Copyright 2014 - Squad. All rights reserved.</p>
                    </div>
                </div>	
            </div>
        </footer>
    </body>
</html>

